= Unused Image Detector for AsciiDoc Projects

= Goal
The Goal of this project was to not waste 10 hours manually remove image unused images in my studies.

= Presentation

[source, shell]
├── LICENSE
├── Makefile
├── README.asciidoc
├── demo-1
│   ├── assets
│   │   ├── should-move-to-unused-1.png
│   │   └── yes.png
│   ├── demo-3
│   │   └── assets
│   │       └── should-move-to-unused-3.png
│   └── demo.asciidoc
├── demo-2
│   └── assets
│       └── should-move-to-unused-2.png
├── demo.asciidoc
└── main.py


[source, shell]
$ make craft
mkdir -p demo-1/assets demo-2/assets demo-1/demo-3/assets
touch ./demo-1/assets/yes.png
touch ./demo-1/assets/should-move-to-unused-1.png
touch ./demo-2/assets/should-move-to-unused-2.png
touch ./demo-1/demo-3/assets/should-move-to-unused-3.png
cat ./demo.asciidoc > ./demo-1/demo.asciidoc
$ make      
python3 main.py
Browsing: .
Browsing: ./demo-1
./demo-1/assets/should-move-to-unused-1.png is unused
Browsing: ./demo-1/assets
Browsing: ./demo-1/demo-3
./demo-1/demo-3/assets/should-move-to-unused-3.png is unused
Browsing: ./demo-1/demo-3/assets
Browsing: ./demo-2
./demo-2/assets/should-move-to-unused-2.png is unused
Browsing: ./demo-2/assets
$ make clean
rm -rf unused-images demo-1 demo-2

= Notes
* The script is hardcoded to look for assets directory in each sub.
* The unused-dir is intentional in case you need them.

= License 
Script is signed under LGPLv3
